name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build, no default features
      run: cargo build --verbose --no-default-features
    - name: Run tests, no default features
      run: cargo test --verbose --no-default-features
    - name: Build, all features
      run: cargo build --verbose --all-features
    - name: Build, all features
      run: cargo test --verbose --all-features
