name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: ["", "--features laz", "--features laz-parallel"]
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose ${{ matrix.features }}
      - name: Clippy
        run: cargo clippy --verbose ${{ matrix.features }}
      - name: Run tests
        run: cargo test --verbose ${{ matrix.features }}
